name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        working-directory: /DockerBuild/GPT-SoVITS
        run: docker build -t oasistem/gpt-sovits:latest

      - name: Push Docker image to Docker Hub
        working-directory: /DockerBuild/GPT-SoVITS
        run: docker push oasistem/gpt-sovits:latest
